# Molecule configuration
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: molecule_local/instance
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible